/**
 * @fileoverview The FCC market-area table (`data/market-states.json`, regenerated by
 * `scripts/build-market-states.ts` from FCC area definitions): the USPS states each market
 * code (`CMA693`, `MTA010`, `PEA416`) covers, and the state of each county FIPS prefix. Read by
 * the market-side state filter of `searchFrequencies`.
 * @module services/uls/market-states
 */

import table from './data/market-states.json' with { type: 'json' };

const CODES_BY_STATE = new Map<string, string[]>();
for (const [code, states] of Object.entries(table.markets)) {
  for (const state of states) {
    const codes = CODES_BY_STATE.get(state);
    if (codes) codes.push(code);
    else CODES_BY_STATE.set(state, [code]);
  }
}

const FIPS_PREFIX_BY_STATE = new Map(
  Object.entries(table.fipsStates).map(([prefix, state]) => [state, prefix]),
);

/** Market codes whose FCC area reaches `state`; a market spanning several states is listed under each. */
export function marketCodesIn(state: string): readonly string[] {
  return CODES_BY_STATE.get(state) ?? [];
}

/** The two-digit FIPS prefix of `state`'s counties, as county-coded markets (`C`/`D` + FIPS) carry it. */
export function countyFipsPrefix(state: string): string | undefined {
  return FIPS_PREFIX_BY_STATE.get(state);
}

/** Codes the table lists with no state: the Gulf of Mexico areas. */
export const STATELESS_MARKET_CODES: readonly string[] = Object.entries(table.markets)
  .filter(([, states]) => states.length === 0)
  .map(([code]) => code);
